### ISSUE TITLE
Agree button still visible after agreeing

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#157] opened 2015-04-16 19:50 UTC
"Agree" button persists after tapping it.

**Comment by kueda** [comment] 2015-04-17 00:41
To be clear, the issue is that the "Agree" button appears next to identifications with the same taxon as your own identification, which tends to cause confusion for people and results in them hitting it again and again, only to add numerous identifications of the same taxon.

**Comment by alexshepard** [comment] 2015-04-17 01:00
We have the same problem only much worse on the explore tab.

**Comment by alexshepard** [comment] 2015-07-11 02:09
done in 4f2b551, in 2.5.8

**Comment by alexshepard** [comment] 2015-07-11 02:10
closing as duplicate of #108

**Closed by alexshepard** 2015-07-11 02:10 UTC
