### ISSUE TITLE
Allow user's Place setting to affect common name displays in iOS app

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#408] opened 2017-08-28 03:52 UTC
An Argentinian user has his phone set to Spanish, but he says that the Mexican and Spanish common names (default for Spanish language) are very different from what they use in Argentina or in the English guide book(s) he uses. He's asking that common names be displayed in a language different from his phone's language. 

I imagine this might be done by having the user's Place setting (in their Account page on the web) affect common names in the app. So for instance, he could choose a Place that uses English and then see the English common names in the app. Would this be possible?

He's also interested in adding more Argentinian common names to the site (I told him how to do it) so hopefully in the future Argentinian Spanish can be more useful in this use case.

**Comment by alexshepard** [comment] 2017-08-29 00:49
We send the locale, which contains both the place and the language, when we fetch taxa from the server. I think the issue here is that we don't have Argentine names on the site.

**Comment by alexshepard** [comment] 2017-08-29 01:01
Reopening, the server doesn't work quite how I thought it did!

**Comment by naturalistmellis** [comment] 2017-09-20 23:07
To me this sounds like a duplicate of #177 and #176.

**Comment by alexshepard** [comment] 2017-09-24 21:24
@tiwane this should be working based on server changes, and it’s working for me. When I switch my iNat place to Germany without changing either my device locale or language, I see the Me tab and the Explore tab taxa names in German (where there actually common names in German).

**Comment by tiwane** [comment] 2017-09-24 22:46
Yup, looking good, Alex. Thanks!

**Closed** 2017-09-24 22:56 UTC
Labels: improvements, ready
