### ISSUE TITLE
No focus box, focus lock, or exposure control in camera mode.

### ISSUE THREAD

**Issue by mixxster** [inaturalist/INaturalistIOS#388] opened 2017-06-17 14:16 UTC
Since iNaturalist relies almost entirely on photos to reach Research Grade for most observations, it would be very beneficial to improve the functionality of camera mode.

Can the camera mode be updated to include a focus box, focus lock, and exposure control? I wish the iNaturalist camera was more functional and behaved more like the default iOS camera, Camera+, or similar camera apps.

When photographing moving insects, species in tricky lighting, or tiny plant parts, all of these features can very important to getting a good shot. This is why I haven't been using the iNaturalist camera mode, but it would save me a lot of time if it were more capable.

**Comment by mixxster** [comment] 2017-06-17 14:28
I'm new to github, and don't know how to merge or delete my issue, but it looks like my issue is a duplicate of #260 

Although I am also requesting focus lock and exposure control in addition to the focus box.

**Comment by alexshepard** [comment] 2017-06-17 20:03
Duplicate of #260. This is on my radar, but not trivial to do right now.

**Closed by alexshepard** 2017-06-17 20:03 UTC
