### ISSUE TITLE
Show error when any request gets a 401 error

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#420] opened 2017-12-09 00:22 UTC
We just made it so suspending a user revokes their OAuth access tokens, so any subsequent requests should get a 401 response. This seems to cause the iOS app to crash on upload and even startup. Instead of that, can we show generic `Not Authorized` alert in those cases. Text can be something like

**Not Authorized**
You don't have permission to do that. Your account may have been suspended. Please contact help@inaturalist.org

**Comment by alexshepard** [comment] 2017-12-09 19:07
The crash appears to be caused by restkit releasing object loaders too early when they fail. We have a workaround in place, but it doesn't appear to be working. I've got a fix queued up.

There was already code in the app to handle 401 errors, we prompt the user to login. Should suspended really return 401 instead of 403?

**Comment by alexshepard** [comment] 2017-12-09 19:29
The crash on startup seems to be related to auto upload, so it's just the one crash.

**Comment by kueda** [comment] 2017-12-09 19:37
403 would definitely be better, but at present I think achieving that will require forking some 3rd party software that we use. Still investigating...

**Comment by alexshepard** [comment] 2018-04-03 19:10
released in 2.7.6

**Closed by alexshepard** 2018-04-03 19:10 UTC
Labels: bugs
