### ISSUE TITLE
Observation Description shown instead of species name in Me section if no CID

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#278] opened 2016-05-18 02:47 UTC
I uploaded an observation using the new web uploader (http://www.inaturalist.org/observations/3200547) and in Me section of the latest TestFlight version (2.6.11 (325)) the description text displays instead of the species name.
![slack for ios upload](https://cloud.githubusercontent.com/assets/15896181/15345944/22e4d9d0-1c68-11e6-85ce-11203010a1f4.jpg)

**Comment by alexshepard** [comment] 2017-04-28 22:00
if there's no description, we show unknown here.

not able to reproduce via the web app anymore, but still happens if you make the obs on the phone, then sign out and back in before someone can confirm id, producing a community id.

**Comment by alexshepard** [comment] 2017-06-12 17:13
fixed in 4bf5c2c437f16947adc44600b7f3668f0c031eb4 which is out as part of 2.6.26

**Closed** 2017-07-05 17:45 UTC
Labels: bugs, ready
