### ISSUE TITLE
Some images not displaying/notification weirdness v. 2.7

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#392] opened 2017-06-27 12:15 UTC
This might be a weird edge case, but I'm going to put it out there in case the underlying issues crop up somewhere else.

I made several observations (mostly taking photos within the app) with auto sync off. Several didn't have IDs at all. Later I uploaded them on wifi yesterday evening from v 2.6.26 build 437. Then I went to look at them in v. 2.7 build 453 on a different phone (so I could use the new image recognition tool, but people identified them all super fast), and the observations that didn't have IDs but did have photos are showing only iconic taxa in v. 2.7. I can see the photos on my other phone on v. 2.6.26.

Perhaps relatedly, notifications aren't working as expected. Even though I haven't tapped on the notifications tab in v. 2.7, it seems to be suppressing the notifications on the other devise (2.6.26) and (more importantly) the website. This is undesirable since I prefer to go through notifications on the website (especially when I have 42!). 

I think to replicate this you:
1. Turn off auto sync on a device running 2.6.26
2. Make some observations but don't add any IDs.
3. Upload
(get some other people to add IDs)
4. Sync/view on another device with 2.7.
5. See that there are no images on the device running 2.7.
6. See notifications, but don't tap on them.
7. See that you have no notifications visible on the web.

Like I said, I know it's probably unlikely for someone to be running two different versions on two different iOS devices, but the notifications issues is a bigger concern for me and these are the specific circumstances in which I observed the problem.

**Comment by carrieseltzer** [comment] 2017-06-28 00:18
Even weirder--I can't see or clear the notifications that I see in 2.7 on my observations where I didn't enter an initial id myself. Sorry I can't insert screen shots from my phone now but can later once someone replies and I get an email notification. (Sorry, my travel devices are complicated)

**Comment by alexshepard** [comment] 2017-06-29 00:06
images not loading for observations made on a different iOS device should be fixed in 553b4b4b6889d2b02fbcad774d888413695025ba

I can't reproduce your notifications issue, but try again with the next release on testflight (should be in an hour or so).

**Comment by alexshepard** [comment] 2017-08-11 19:56
@carrieseltzer are you still seeing this behavior in 2.7 now that it's out?

**Comment by carrieseltzer** [comment] 2017-08-11 20:10
Will charge up my other phone to try this in about an hour.

**Comment by carrieseltzer** [comment] 2017-08-11 21:48
I don't think this is happening anymore. As an aside, my phone thinks it is July 7 instead of August 11, so it's interesting to see how the app handles observations from the "future"... looks fine! Thanks, Alex.

**Comment by alexshepard** [comment] 2017-09-20 21:47
closing since I think this is all fixed

**Closed by alexshepard** 2017-09-20 21:47 UTC
