### ISSUE TITLE
Observation Activity Screen: ID Search Screen Does Not Dismiss When Tapping Done

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#166] opened 2015-05-08 00:35 UTC
When tapping "Add ID" from Observation Activity screen, the "Done" button does not dismiss the screen if the search field is empty
 <br>
### Steps to Reproduce

From "Observation Activity" screen, Tap "Add ID"
Do not enter text in Search field on "Search species" screen
Tap "Done" in upper right corner
 <br>
### Expected Behavior

Done button dismisses screen.
 <br>
### Actual Behavior

Done button does not dismiss screen and you are trapped on screen until selecting an ID
 <br>

### Device
iPhone 5 - Test Flight: Version 2.5.5 (139) - OS 8.1.3 (12B466)

**Comment by alexshepard** [comment] 2015-07-11 02:31
dupe of #19

**Closed by alexshepard** 2015-07-11 02:31 UTC
